# Generated by Django 5.2.7 on 2025-10-14 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ot', '0002_makeorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='makeorder',
            name='categories',
            field=models.ManyToManyField(to='ot.category', verbose_name='Categorias'),
        ),
    ]
